### PR TITLE
climate Prediction using Machine Learning

### PR DESCRIPTION
**Pull request by siddeshas07**

### CODE REVIEW

**Comment by SARTHAK2511** [comment]
Hey  @siddeshas07  , please remove the attrition prediction as it is already  in the repo , once done I'll merge ur files

**Comment by siddeshas07** [comment]
Kidney Disease Prediction with machine learning  please merg my pull request

**Comment by SARTHAK2511** [comment]
Thank you for your contribution , please give a star to the repo and i will not accept the attrition project as it has been already in the repo

**Comment by siddeshas07** [comment]
I have given Star 🌟 please merge pull request

**Comment by siddeshas07** [comment]
Only 2 are remaining

**Comment by SARTHAK2511** [comment]
I have merged all in the morning only

**Pull request merged**
