### PR TITLE
Movie recommendation system

### PR DESCRIPTION
**Pull request by KushalPareek**
Predict 5 movies based on imbd rating

### CODE REVIEW

**Comment by KushalPareek** [comment]
Please check it and let me know whether it is valid or not ?

**Comment by SARTHAK2511** [comment]
Its all good ,but u have used kaggle notebook , please just specify the dataset link in comments of your code , I'll merge it then

**Comment by KushalPareek** [comment]
Added dataset link in my code. 
https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata

**Comment by KushalPareek** [comment]
I have done the changes.Please look.

Thanks & Regards
Kushal Pareek

**Comment by SARTHAK2511** [comment]
Thank you for contributing

**Pull request merged**
