### PR TITLE
Visualization on IPL data set

### PR DESCRIPTION
**Pull request by nitishwaa**
Kindly confirm my merge request

### CODE REVIEW

**Comment by SARTHAK2511** [comment]
Thank you for your contribution ✨

**Comment by nitishwaa** [comment]
I committed two projects but in my hacktoberfest account only one is reflected. Any idea why?

**Comment by SARTHAK2511** [comment]
There's only one pr allowed per respo

**Comment by SARTHAK2511** [comment]
For Hacktoberfest

**Pull request merged**
